[package]
name = "rust_paillier718"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpaillier = "0.5.0"
num-bigint = "0.4"
num-traits = "0.2.15"